apiVersion: efs.aws.upbound.io/v1beta1
kind: FileSystemPolicy
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: User needs to add the ARN of the FileSystem to the policy manually.
  name: kevin-kimanzi-ap-filesystempolicy
spec:
  forProvider:
    bypassPolicyLockoutSafetyCheck: true
    fileSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: efs
    policy: |
      {
          "Version": "2012-10-17",
          "Id": "ExamplePolicy01",
          "Statement": [
              {
                  "Sid": "ExampleStatement01",
                  "Effect": "Allow",
                  "Principal": {
                      "AWS": "*"
                  },
                  "Resource": "<file system ARN>",
                  "Action": [
                      "elasticfilesystem:ClientMount",
                      "elasticfilesystem:ClientWrite"
                  ],
                  "Condition": {
                      "Bool": {
                          "aws:SecureTransport": "true"
                      }
                  }
              }
          ]
      }
    region: us-west-1